SELECT * FROM dba_objects
WHERE object_name LIKE '%SES%HIST%'

SELECT * FROM DBA_HIST_DB_CACHE_ADVICE
WHERE SNAP_ID = (SELECT MAX(SNAP_ID ) FROM DBA_HIST_DB_CACHE_ADVICE)


SELECT * FROM DBA_HIST_PGA_TARGET_ADVICE
WHERE SNAP_ID = (SELECT MAX(SNAP_ID ) FROM DBA_HIST_SHARED_POOL_ADVICE)


SELECT * FROM DBA_HIST_PGA_TARGET_ADVICE
WHERE SNAP_ID = (SELECT MAX(SNAP_ID ) FROM DBA_HIST_PGA_TARGET_ADVICE)

SELECT * FROM DBA_HIST_JAVA_POOL_ADVICE
WHERE SNAP_ID = (SELECT MAX(SNAP_ID ) FROM DBA_HIST_JAVA_POOL_ADVICE)

SELECT * FROM DBA_HIST_MTTR_TARGET_ADVICE
WHERE SNAP_ID = (SELECT MAX(SNAP_ID ) FROM DBA_HIST_MTTR_TARGET_ADVICE)
