CREATE TABLESPACE DWHDATA DATAFILE 
  '+DATA' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE 100M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 256K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ETLADMINDATA DATAFILE 
  '+DATA' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE 100M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 256K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE DWHRODATA DATAFILE 
  '+DATA' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE 100M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 256K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ERMODDATA DATAFILE 
  '+DATA' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE 100M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 256K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ETLDATA DATAFILE 
  '+DATA' SIZE 64M AUTOEXTEND ON NEXT 64M MAXSIZE 256M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 256K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ETLDEVDATA DATAFILE 
  '+DATA' SIZE 64M AUTOEXTEND ON NEXT 64M MAXSIZE 256M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 256K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE DWHAUXDATA DATAFILE 
  '+DATA' SIZE 64M AUTOEXTEND ON NEXT 64M MAXSIZE 256M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 256K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE DWH_MIN_DATA DATAFILE 
  '+DATA' SIZE 512M AUTOEXTEND ON NEXT 512M MAXSIZE 32G
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 256K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE DWH_MIN_INDX DATAFILE 
  '+DATA' SIZE 512M AUTOEXTEND ON NEXT 512M MAXSIZE 32G
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 256K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE STG_MIN_DATA DATAFILE 
  '+DATA' SIZE 512M AUTOEXTEND ON NEXT 512M MAXSIZE 32G
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 256K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE STG_MIN_INDX DATAFILE 
  '+DATA' SIZE 512M AUTOEXTEND ON NEXT 512M MAXSIZE 32G
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 256K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SRC_MIN_DATA DATAFILE 
  '+DATA' SIZE 512M AUTOEXTEND ON NEXT 512M MAXSIZE 32G
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 256K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE DWH_MED_DATA DATAFILE 
  '+DATA' SIZE 512M AUTOEXTEND ON NEXT 512M MAXSIZE 32G
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 2M
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE DWH_MED_INDX DATAFILE 
  '+DATA' SIZE 512M AUTOEXTEND ON NEXT 512M MAXSIZE 32G
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 2M
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE STG_MED_DATA DATAFILE 
  '+DATA' SIZE 512M AUTOEXTEND ON NEXT 512M MAXSIZE 32G
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 2M
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE STG_MED_INDX DATAFILE 
  '+DATA' SIZE 512M AUTOEXTEND ON NEXT 512M MAXSIZE 32G
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 2M
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SRC_MED_DATA DATAFILE 
  '+DATA' SIZE 512M AUTOEXTEND ON NEXT 512M MAXSIZE 32G
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 2M
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE DWH_MAX_DATA DATAFILE 
  '+DATA' SIZE 512M AUTOEXTEND ON NEXT 512M MAXSIZE 32G
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 4M
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE DWH_MAX_INDX DATAFILE 
  '+DATA' SIZE 512M AUTOEXTEND ON NEXT 512M MAXSIZE 32G
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 4M
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE STG_MAX_DATA DATAFILE 
  '+DATA' SIZE 512M AUTOEXTEND ON NEXT 512M MAXSIZE 32G
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 4M
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE STG_MAX_INDX DATAFILE 
  '+DATA' SIZE 512M AUTOEXTEND ON NEXT 512M MAXSIZE 32G
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 4M
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SRC_MAX_DATA DATAFILE 
  '+DATA' SIZE 512M AUTOEXTEND ON NEXT 512M MAXSIZE 32G
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 4M
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE DWH_HUGE_DATA DATAFILE 
  '+DATA' SIZE 512M AUTOEXTEND ON NEXT 512M MAXSIZE 32G
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 8M
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE DWH_HUGE_INDX DATAFILE 
  '+DATA' SIZE 512M AUTOEXTEND ON NEXT 512M MAXSIZE 32G
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 8M
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE STG_HUGE_DATA DATAFILE 
  '+DATA' SIZE 512M AUTOEXTEND ON NEXT 512M MAXSIZE 32G
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 8M
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE STG_HUGE_INDX DATAFILE 
  '+DATA' SIZE 512M AUTOEXTEND ON NEXT 512M MAXSIZE 32G
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 8M
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SRC_HUGE_DATA DATAFILE 
  '+DATA' SIZE 512M AUTOEXTEND ON NEXT 512M MAXSIZE 32G
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL uniform size 8M
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

