CREATE INDEX BUILD.BF_LOGS_UID_NCHAR ON BUILD.BF_LOGS
(SYS_OP_C2C("BF_UID"))
LOGGING
TABLESPACE BUILDFORGE
NOPARALLEL;

ALTER INDEX BUILD.BF_LOGS_UID_NCHAR
  MONITORING USAGE;
  
  CREATE INDEX BUILD.BF_LOGB_UID_NCHAR ON BUILD.BF_LOGBUCKETS
(SYS_OP_C2C("BF_UID"))
LOGGING
TABLESPACE BUILDFORGE
NOPARALLEL;

ALTER INDEX BUILD.BF_LOGB_UID_NCHAR
  MONITORING USAGE;
  
  CREATE INDEX BUILD.BF_STORE_UID_NCHAR ON BUILD.BF_STORE
(SYS_OP_C2C("BF_UID"))
LOGGING
TABLESPACE BUILDFORGE
NOPARALLEL;

ALTER INDEX BUILD.BF_STORE_UID_NCHAR
  MONITORING USAGE;


CREATE INDEX BUILD.BF_STORE_UID_PART_NCHAR ON BUILD.BF_STORE
(SYS_OP_C2C("BF_UID"), TO_NCHAR("BF_PART"))
LOGGING
TABLESPACE BUILDFORGE
NOPARALLEL;

ALTER INDEX BUILD.BF_STORE_UID_PART_NCHAR
  MONITORING USAGE;