CREATE TABLESPACE DEV DATAFILE 
  '/oradata/oraint01/OLINT/dev01.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE IDX DATAFILE 
  '/oradata/oraint01/OLINT/idx01.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TEMPORARY TABLESPACE TEMPSPACE1 TEMPFILE 
  '/oradata/oraint01/OLINT/tempspace01.dbf' SIZE 20M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;

CREATE USER CCSOWNER
  IDENTIFIED BY VALUES '550C0E2429A34315'
  DEFAULT TABLESPACE DEV
  TEMPORARY TABLESPACE TEMPSPACE1
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for CCSOWNER 
  GRANT CONNECT TO CCSOWNER;
  ALTER USER CCSOWNER DEFAULT ROLE ALL;
  -- 6 System Privileges for CCSOWNER 
  GRANT CREATE TRIGGER TO CCSOWNER;
  GRANT CREATE VIEW TO CCSOWNER;
  GRANT CREATE SYNONYM TO CCSOWNER;
  GRANT CREATE TYPE TO CCSOWNER;
  GRANT CREATE SEQUENCE TO CCSOWNER;
  GRANT CREATE TABLE TO CCSOWNER;
CREATE USER PDUSER
  IDENTIFIED BY VALUES 'D236193742BA004B'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMPSPACE1
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for PDUSER 
  GRANT CONNECT TO PDUSER;
  ALTER USER PDUSER DEFAULT ROLE ALL;
  
CREATE USER USRCCS
  IDENTIFIED BY VALUES '6E569357F5B7D89E'
  DEFAULT TABLESPACE DEV
  TEMPORARY TABLESPACE TEMPSPACE1
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for USRCCS 
  GRANT CONNECT TO USRCCS;
  ALTER USER USRCCS DEFAULT ROLE ALL;
  -- 1 System Privilege for USRCCS 
  GRANT SELECT ANY TABLE TO USRCCS;
