SELECT FLASHBACK_ON,current_scn FROM V$DATABASE;

select oldest_flashback_scn from v$flashback_database_log;


select name,value from v$parameter where upper(name) in
('DB_FLASHBACK_RETENTION_TARGET','DB_RECOVERY_FILE_DEST_SIZE',
'DB_RECOVERY_FILE_DEST','LOG_ARCHIVE_DEST_1');


ALTER SYSTEM SET DB_FLASHBACK_RETENTION_TARGET=600;

ALTER SYSTEM SET DB_RECOVERY_FILE_DEST_SIZE=20G;


SELECT SCN_TO_TIMESTAMP( 34530329701 ) FROM DUAL;

SELECT TIMESTAMP_TO_SCN(TO_TIMESTAMP('2009-10-09 16:46:00', 'YYYY-MM-DD HH24:MI:SS') ) FROM DUAL;

FLASHBACK DATABASE TO SCN 34570271536;

--kontrol için
ALTER DATABASE OPEN READ ONLY;


ALTER DATABASE OPEN RESETLOGS;

--flashback'ten vazgeçersek
recover database;

ALTER DATABASE FLASHBACK OFF;



/* FLASHBACK LOG'LARI GOSTERIR */
SELECT * FROM V$FLASHBACK_DATABASE_LOGFILE;

/* GIDILEBILECEK EN ESKI FLASHBACK ZAMANINI GOSTERIR */
SELECT * FROM V$FLASHBACK_DATABASE_LOG;

/* BUTUN TABLESPACE'LER ICIN FLASHBACK ACIK OLMALIDIR */
SELECT NAME TBS_NAME,FILE_NAME DB_FILE,FLASHBACK_ON FB_LOGGING,
ONLINE_STATUS STATUS
FROM V$TABLESPACE,DBA_DATA_FILES WHERE NAME=TABLESPACE_NAME;

/* FLASHBACK RECOVERY AREA DOLULUK ORANINI GOSTERIR */
select
name,
to_char(space_limit, '999,999,999,999') as space_limit,
to_char(space_limit - space_used + space_reclaimable,
'999,999,999,999') as space_available,
round((space_used - space_reclaimable)/space_limit * 100, 1) as pct_full
from
v$recovery_file_dest;
