
CREATE INDEX FRAUDSTAR.IDX$$_03250001 ON FRAUDSTAR.AUTHORIZATIONS
(STATUS, TRANSACTIONDATE)
LOGGING
TABLESPACE FS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX FRAUDSTAR.IDX$$_03250003 ON FRAUDSTAR.AUTHORIZATIONS
(CARDNO, ASSIGNUSER, TRANSACTIONDATE)
NOLOGGING
TABLESPACE FS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX FRAUDSTAR.IDX$$_03250004 ON FRAUDSTAR.AUTHORIZATIONS
(ACTIONCODE, REFNO)
LOGGING
TABLESPACE FS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;
