CREATE TABLESPACE APPS_TS_TX_DATA_P DATAFILE 
  '/glpdata01/ORAGLPER/a_txn_data01.dbf' SIZE 256M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
  '/glpdata02/ORAGLPER/a_txn_data02.dbf' SIZE 256M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
  '/glpdata03/ORAGLPER/a_txn_data03.dbf' SIZE 256M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
  '/glpdata04/ORAGLPER/a_txn_data04.dbf' SIZE 256M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
  '/glpdata05/ORAGLPER/a_txn_data05.dbf' SIZE 256M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
  '/glpdata06/ORAGLPER/a_txn_data06.dbf' SIZE 256M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 128K
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE APPS_TS_TX_IDX_P DATAFILE 
  '/glpdata01/ORAGLPER/a_txn_idx01.dbf' SIZE 256M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
  '/glpdata02/ORAGLPER/a_txn_idx02.dbf' SIZE 256M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
  '/glpdata03/ORAGLPER/a_txn_idx03.dbf' SIZE 256M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
  '/glpdata04/ORAGLPER/a_txn_idx04.dbf' SIZE 256M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
  '/glpdata05/ORAGLPER/a_txn_idx05.dbf' SIZE 256M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
  '/glpdata06/ORAGLPER/a_txn_idx06.dbf' SIZE 256M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 128K
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE TSEBSHLDATA_0310_P DATAFILE 
  '/glpdata01/ORAGLPER/tsebshldata0310_01.dbf' SIZE 256M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
  '/glpdata02/ORAGLPER/tsebshldata0310_02.dbf' SIZE 256M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
  '/glpdata03/ORAGLPER/tsebshldata0310_03.dbf' SIZE 256M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
  '/glpdata04/ORAGLPER/tsebshldata0310_04.dbf' SIZE 256M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
  '/glpdata05/ORAGLPER/tsebshldata0310_05.dbf' SIZE 256M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
  '/glpdata06/ORAGLPER/tsebshldata0310_06.dbf' SIZE 256M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING
DEFAULT STORAGE ( 
                  INITIAL     40K
                  NEXT        40K
                  MINEXTENTS  1
                  MAXEXTENTS  UNLIMITED
                  PCTINCREASE 50
                )
ONLINE
PERMANENT
EXTENT MANAGEMENT DICTIONARY
BLOCKSIZE 8K
FLASHBACK ON;