ALTER TABLE SWITCH.INS_MODULE_INFO ADD (TO_REP_CNT           NUMBER(2) DEFAULT 1 NOT NULL);


ALTER TABLE SWITCH.INS_MODULE_INFO ADD (TO_REV_CNT           NUMBER(2) DEFAULT 3 NOT NULL);


ALTER TABLE SWITCH.INS_MODULE_INFO ADD (SEND_SIGNON          NUMBER(1) DEFAULT 0 NOT NULL);


ALTER TABLE SWITCH.INS_MODULE_INFO ADD (SEND_ECHO            NUMBER(1) DEFAULT 0 NOT NULL);


--------------------------------------

ALTER TABLE SWITCH.TRNX_LOG ADD (F47                  VARCHAR2(16) DEFAULT ' '		 NOT NULL);


ALTER TABLE SWITCH.TRNX_LOG ADD (DEST_ORIG            CHAR(2) DEFAULT ' '		 NOT NULL);


ALTER TABLE SWITCH.TRNX_LOG ADD (SOURCE_ORIG          CHAR(2) DEFAULT ' '		 NOT NULL);


ALTER TABLE SWITCH.TRNX_LOG ADD (F12                  NUMBER(6) DEFAULT -1 NOT NULL);


ALTER TABLE SWITCH.TRNX_LOG ADD (F13                  NUMBER(8) DEFAULT -1 NOT NULL);


ALTER TABLE SWITCH.TRNX_LOG ADD (F3_PROCCODE_TO_ACC   NUMBER(2) DEFAULT -1 NOT NULL);


ALTER TABLE SWITCH.TRNX_LOG ADD (F3_PROCCODE_TRAN_TYPE NUMBER(2) DEFAULT -1 NOT NULL);


ALTER TABLE SWITCH.TRNX_LOG ADD (F3_PROCCODE_TYPE_OF_ACC NUMBER(2) DEFAULT -1 NOT NULL);


ALTER TABLE SWITCH.TRNX_LOG ADD (F51                  NUMBER(3) DEFAULT -1 NOT NULL);


ALTER TABLE SWITCH.TRNX_LOG ADD (REV_TRNX_CODE        CHAR(2) DEFAULT ' '		 NOT NULL);


ALTER TABLE SWITCH.TRNX_LOG ADD (REV_TRNX_SUB_CODE    CHAR(2) DEFAULT ' '		 NOT NULL);


ALTER TABLE SWITCH.TRNX_LOG ADD (REV_INC_MTI          NUMBER(4) DEFAULT -1 NOT NULL);


ALTER TABLE SWITCH.TRNX_LOG ADD (F16                  NUMBER(8) DEFAULT -1 NOT NULL);


ALTER TABLE SWITCH.TRNX_LOG ADD (ADV_REQ              CHAR(1) DEFAULT 'N' NOT NULL);


ALTER TABLE SWITCH.TRNX_LOG ADD (ADV_RESP             CHAR(1) DEFAULT 'N' NOT NULL);


ALTER TABLE SWITCH.TRNX_LOG ADD (ADV_CNT              NUMBER(2) DEFAULT 0 NOT NULL);


ALTER TABLE SWITCH.TRNX_LOG ADD (TC_UPLOAD            CHAR(1) DEFAULT 'I' NOT NULL);

---------------------------------------
-- F55_9F1E kolonu için belirtmediðiniz halde VARCHAR2(16) -> VARCHAR2(8) dönüþümü var modelde
---------------------------------------


ALTER TABLE SWITCH.SWC_LOG ADD (F47                  VARCHAR2(16) DEFAULT ' '		 NOT NULL);


ALTER TABLE SWITCH.SWC_LOG ADD (VISA_MSG_HDR         VARCHAR2(32) DEFAULT ' '		 NOT NULL);


ALTER TABLE SWITCH.SWC_LOG ADD (F48                  VARCHAR2(255) DEFAULT ' '		 NOT NULL);


ALTER TABLE SWITCH.SWC_LOG ADD (DEST_ORIG            CHAR(2) DEFAULT ' '		 NOT NULL);


ALTER TABLE SWITCH.SWC_LOG ADD (SOURCE_ORIG          CHAR(2) DEFAULT ' '		 NOT NULL);


ALTER TABLE SWITCH.SWC_LOG ADD (F60                  VARCHAR2(4) DEFAULT ' '		 NOT NULL);


ALTER TABLE SWITCH.SWC_LOG MODIFY (F54_ADD_AMNTS_AMNT VARCHAR2(12));

