CREATE USER ODAK
  IDENTIFIED BY VALUES '0EB89491016F0055'
  DEFAULT TABLESPACE TSODAK
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT LOCK;
  -- 1 Tablespace Quota for ODAK 
  ALTER USER ODAK QUOTA UNLIMITED ON TSODAK;

CREATE USER TAX
  IDENTIFIED BY VALUES 'EC949FB2C86CCCE1'
  DEFAULT TABLESPACE TSTAX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT LOCK;
  -- 1 Tablespace Quota for TAX 
  ALTER USER TAX QUOTA UNLIMITED ON TSTAX;
  -- 3 Object Privileges for TAX 
    GRANT ALTER, SELECT ON TAX.TAX_LINKID_SEQUENCE TO TAX;
    GRANT ALTER, SELECT ON TAX.TAX_POSTING_SEQEUNCE TO TAX;
    GRANT ALTER, SELECT ON TAX.TAX_TRANSACTION_SEQUENCE TO TAX;

CREATE USER USRODAK
  IDENTIFIED BY VALUES '054F968CB1A198F0'
  DEFAULT TABLESPACE TSODAK
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for USRODAK 
  GRANT CONNECT TO USRODAK;
  ALTER USER USRODAK DEFAULT ROLE ALL;
  
  CREATE USER USRREPORT
  IDENTIFIED BY VALUES '943A61646E97080A'
  DEFAULT TABLESPACE TSODAK
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for USRREPORT 
  GRANT CONNECT TO USRREPORT;
  ALTER USER USRREPORT DEFAULT ROLE ALL;
  
  CREATE USER USRSECURE
  IDENTIFIED BY VALUES 'AA11B19433AD1508'
  DEFAULT TABLESPACE TSODAK
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for USRSECURE 
  GRANT CONNECT TO USRSECURE;
  ALTER USER USRSECURE DEFAULT ROLE ALL;
  
  CREATE USER USRSTAT
  IDENTIFIED BY VALUES 'EF4F44B3DEA1FED8'
  DEFAULT TABLESPACE TSODAK
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for USRSTAT 
  GRANT CONNECT TO USRSTAT;
  ALTER USER USRSTAT DEFAULT ROLE ALL;
  
  CREATE USER USRTAX
  IDENTIFIED BY VALUES 'AA7FABEF84D6D5C5'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for USRTAX 
  GRANT CONNECT TO USRTAX;
  ALTER USER USRTAX DEFAULT ROLE ALL;