select  (SELECT 
/*+PARALLEL(8)*/
         count(*) 
    FROM 
        OBIEE_BIPLATFORM.S_NQ_ACCT LOJIK_LOG_TABLOSU 
        INNER JOIN 
          OBIEE_BIPLATFORM.S_NQ_DB_ACCT FIZIKSEL_LOG_TABLOSU
       ON LOJIK_LOG_TABLOSU.ID = FIZIKSEL_LOG_TABLOSU.LOGICAL_QUERY_ID
   WHERE     LOJIK_LOG_TABLOSU.START_DT =to_date( '17.08.2015','DD.MM.YYYY')
         and FIZIKSEL_LOG_TABLOSU.TIME_SEC<=5
         AND LOJIK_LOG_TABLOSU.QUERY_SRC_CD = 'Report' ) *100 /
 (        SELECT 
/*+PARALLEL(8)*/
         count(*)  
    FROM 
        OBIEE_BIPLATFORM.S_NQ_ACCT LOJIK_LOG_TABLOSU 
        INNER JOIN 
          OBIEE_BIPLATFORM.S_NQ_DB_ACCT FIZIKSEL_LOG_TABLOSU
       ON LOJIK_LOG_TABLOSU.ID = FIZIKSEL_LOG_TABLOSU.LOGICAL_QUERY_ID
   WHERE     LOJIK_LOG_TABLOSU.START_DT =to_date( '17.08.2015','DD.MM.YYYY')
         AND LOJIK_LOG_TABLOSU.QUERY_SRC_CD = 'Report' ) HSA from dual;

         
    
