CREATE TABLE SMODEL.CMN_STATDATA_CSDTP2
(
  STAT_ID             NUMBER                    NOT NULL,
  SYSTEM_DATE         DATE,
  PREPARATION_DATE    DATE,
  FUNCTION_ID         NUMBER(8),
  CHANNEL_ID          NUMBER(2),
  PARTY_ID            NUMBER(9),
  UNIT_ID             NUMBER(5),
  USER_CODE           VARCHAR2(7 BYTE),
  CLIENT_ID           NUMBER(8),
  CLIENT_SEQ          NUMBER(8),
  LANGUAGE_ID         NUMBER(2),
  SENDER_REFERENCE    CHAR(24 BYTE),
  SESION_TICKET       CHAR(32 BYTE),
  ODAK_REFERENCE      CHAR(24 BYTE),
  INCIDENT_REFERENCE  VARCHAR2(30 BYTE),
  MESSAGE_ID          NUMBER(5),
  STAT_DATA_IN        NCLOB,
  STAT_DATA_OUT       NCLOB
)
TABLESPACE TSMODEL
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
           )
LOGGING
PARTITION BY RANGE (SYSTEM_DATE) 
(  
   PARTITION P2007_01 VALUES LESS THAN (TO_DATE(' 2007-02-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSCSTTKYENI0701
    ,  
  PARTITION P2007_02 VALUES LESS THAN (TO_DATE(' 2007-03-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSCSTTKYENI0701
,
  PARTITION P2007_03 VALUES LESS THAN (TO_DATE(' 2007-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSCSTTKYENI0703
,
   PARTITION P2007_04 VALUES LESS THAN (TO_DATE(' 2007-05-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSCSTTKYENI0704
,
  PARTITION P2007_05 VALUES LESS THAN (TO_DATE(' 2007-06-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSCSTTKYENI0705
,
  PARTITION P2007_06 VALUES LESS THAN (TO_DATE(' 2007-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE TSCSTTKYENI0706
,
        PARTITION PMAX VALUES LESS THAN (MAXVALUE)
    LOGGING
    NOCOMPRESS
    TABLESPACE TSCSTTKYENI0706)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



GRANT DELETE, INSERT, SELECT, UPDATE ON  SMODEL.CMN_STATDATA_CSDTP2 TO COMMON;

GRANT DELETE, INSERT, SELECT, UPDATE ON  SMODEL.CMN_STATDATA_CSDTP2 TO TEST;

GRANT DELETE, INSERT, SELECT, UPDATE ON  SMODEL.CMN_STATDATA_CSDTP2 TO YGM_TEMP;