select 'create tablespace '||tablespace_name||' datafile ''/ocfs/racdb00/datasil/'||tablespace_name||'sil.dbf'' SIZE 1M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;' 
from dba_tablespaces  
where contents != 'TEMPORARY' and tablespace_name not in ('SYSTEM','SYS','SYSAUX','UNDOTBS1','UNDOTBS2')

select * from dba_users where default_TABLESPACE IN (
select distinct DEFAULT_TABLESPACE from dba_users
minus
select distinct name from v$tablespace)


select * from dba_users where default_tablespace in(
select default_tablespace from dba_users
minus 
select tablespace_name from dba_tablespaces)

select * from dba_part_tables where def_tablespace_name in( 
select def_tablespace_name from dba_part_tables
minus 
select tablespace_name from dba_tablespaces)

select * from dba_part_indexes where def_tablespace_name in(
select def_tablespace_name from dba_part_indexes
minus 
select tablespace_name from dba_tablespaces)



select tablespace_name from dba_tablespaces 
where contents != 'TEMPORARY' 
and tablespace_name not in ('SYSTEM','SYS','SYSAUX','UNDOTBS1','UNDOTBS2','TSAUDIT_DATA','TSAUDIT_INDEX')

select ''''||file_name||'''' from dba_data_files 
where tablespace_name in (select tablespace_name from dba_tablespaces where contents != 'TEMPORARY' and tablespace_name not in ('SYSTEM','SYS','SYSAUX','UNDOTBS1','UNDOTBS2','TSAUDIT_DATA','TSAUDIT_INDEX'))


select 'ALTER TABLESPACE '||tablespace_name||' READ WRITE;' from dba_tablespaces 
where contents != 'TEMPORARY' and status = 'READ ONLY'
and tablespace_name not in ('SYSTEM','SYS','SYSAUX','UNDOTBS1','UNDOTBS2','TSAUDIT_DATA','TSAUDIT_INDEX')

select 'DROP TABLESPACE '||tablespace_name||';' from dba_tablespaces 
where contents != 'TEMPORARY' 
and tablespace_name not in ('SYSTEM','SYS','SYSAUX','UNDOTBS1','UNDOTBS2','TSAUDIT_DATA','TSAUDIT_INDEX')



exec sys.DBMS_TTS.TRANSPORT_SET_CHECK('TSAFTTP06,TSAFTTP,USERS,TSCSTMV,TSCUST,TSMBRTP,TS_BODOC,GLOBAL_DATA,TSMHBTP,TSCSTTP0605,TSCSTTP,TSCSTTP0604,TSOWBRUNTIME,TSPERFSTAT,TSCSTTP0603,TSISBDBA,TSTOAD,TSUYE00,TSUYE00_INDEX,TSBOSEC,TSBOSEC_NEW,TSEXTRE_INDEX,TSKKITP,TSKKITP_INDEX,TSACH,TSACCTK,TSEXTRE,TSSBRTP,TSACHINDEX,TSCCRTK,TSMAITP,TSMCCTP,TSMEKTP,TSMESTP,TSMFRTP,TSMMTD,TSMUNTP,TSMUSIND,TSORUTK,TSOUTTK,TSMUS,TSMRCTP,TSDEMFIN,SOE,TSCRDTP,TSTUMHES_TEMP,TSPRODEYSIS,TSMRCTP_TEMP,TSTUMHES_DIGER,TSTUMHES,TS_QUEST_INDEX,TS_QUEST,TSMAXI_IX,TSMAXI,TSACHTEMP,TSACHTP,TSBILTP,TSCSTTP0602,TSISLTP,TSISLTP_INDEX,TSTKSTP,TSTKSTP_INDEX,TSSECURITY,TSTXPTP,TSCITIK,TSOWBD,TSCMN,TSOZET7G,TSACCTP,TSCMNRPT,TSCSTTK,TSCSTTK0603,TSMKITP,TSMKOTP,TSCLTTK,EXAMPLE,TSCSTTKYENI0602,TSCSTTKYENI0603,TSCSTTKYENI0605,TSCSTTKYENI0606,TSCSTTKYENI0607,TSCSTTKYENI0608,TSCSTTKYENI0609,TSCSTTKYENI0610,TSCSTTKYENI0611,TSCSTTKYENI0612,TSCSTTKYENI0701,TSACHTP99,TSACHTP00,TSACHTP01,TSACHTP02,TSACHTP03,TSACHTP04,TSACHTP05,TSACHTP06,TSAFTTP07,TSKFTTP,TSKFTTP06,TSKFTTP07,TSODMTP,TSODMTP06,TSODMTP07,TSEFTTP,TSTALTP,TSBSBTP,TSKRMTP,TSCSTTP0606,TSCSTTP0607,TSCSTTP0608,TSCSTTP0609,TSCSTTK0604,PMO_DATA_64K,TSTPEMP,TSTPRSK,TSTPSYS,TSTPTMP,TSTPONL,TSTPSSA,TSMODEL,TSGNRC,TSAPP,TSCSTTKYENI0703,TSCSTTKYENI0704,TSCSTTKYENI0705,TSCSTTKYENI0706,TSLKU_FTP,TSLKU_ISLEM,TSLKU_ONLINE,TSLKU_MUSDUZELTME,TSLKU_MUSHATALI,TSLKU_MUSTERI,TSIMSETL,TSIMS_DBMAVITL_MAVITALR,TSIMS_DBMUSTRR_MUSTERIR_B,TSIMS_DBSUBEMS_SUBERECO,TSSTAGE,TSEP_DBMUSTRR_MUSTERIR_B_P1,TSEP_DBMUSTRR_MUSTERIR_B_P2',TRUE)

SELECT * FROM sys.TRANSPORT_SET_VIOLATIONS

select tablespace_name from dba_tablespaces 
where contents != 'TEMPORARY' 
and tablespace_name not in ('SYSTEM','SYS','SYSAUX','UNDOTBS1','UNDOTBS2','TSAUDIT_DATA','TSAUDIT_INDEX','TSKFTTP06','TSKFTTP07','TSACHINDEX','TSACHTP','TSACHTP99','TSACHTP00','TSACHTP01','TSACHTP02','TSACHTP03','TSACHTP04','TSACHTP05','TSACHTP06') 

select ''''||file_name||'''' from dba_data_files where TABLESPACE_NAME not in  ('SYSTEM','SYS','SYSAUX','UNDOTBS1','UNDOTBS2','TSAUDIT_DATA','TSAUDIT_INDEX','TSKFTTP06','TSKFTTP07','TSACHINDEX','TSACHTP','TSACHTP99','TSACHTP00','TSACHTP01','TSACHTP02','TSACHTP03','TSACHTP04','TSACHTP05','TSACHTP06') 

select ''''||file_name||'''' from dba_data_files where TABLESPACE_NAME in  ('TSKFTTP06','TSKFTTP07','TSACHINDEX','TSACHTP','TSACHTP99','TSACHTP00','TSACHTP01','TSACHTP02','TSACHTP03','TSACHTP04','TSACHTP05','TSACHTP06')

select tablespace_name from dba_tablespaces 
where contents = 'TEMPORARY' 