select S.USERNAME, trunc(sum(I.BLOCK_CHANGES/1024/1024)) MB from v$session s , V$SESS_IO i 
where S.SID = I.SID
group by username
order by 2 desc ;


SELECT S1.SID, S1.SERIAL#, S1.USERNAME, S1.PROGRAM, I1.BLOCK_CHANGES 
FROM V$SESSION S1, V$SESS_IO I1 WHERE S1.SID = I1.SID ORDER BY 5 DESC, 1, 2, 3, 4;


SELECT S1.SID, S1.SERIAL#,S1.USERNAME, S1.PROGRAM, T1.USED_UBLK, T1.USED_UREC 
FROM V$SESSION S1, V$TRANSACTION T1 WHERE S1.TADDR = T1.ADDR ORDER BY 5 DESC, 6 DESC, 1, 2, 3, 4;


SELECT S1.SID, S1.USERNAME, R1.NAME, T1.START_TIME, T1.USED_UBLK , T1.USED_UREC 
FROM V$SESSION S1, V$TRANSACTION T1, V$ROLLNAME R1 WHERE T1.ADDR = S1.TADDR AND R1.USN = T1.XIDUSN;