SELECT 'DROP SYNONYM ' || SYNONYM_NAME||';'  FROM dba_SYNONYMS WHERE TABLE_OWNER=UPPER('RPM');

SELECT 'CREATE SYNONYM '
    || OBJECT_NAME || ' FOR RPM' || '.' || OBJECT_NAME ||';'
    FROM DBA_OBJECTS WHERE OWNER=UPPER('RPM')
    AND OBJECT_TYPE IN ('TABLE','SEQUENCE','PACKAGE','FUNCTION','PROCEDURE','TYPE');
    
    
    
    select object_name from dba_objects where OWNER=UPPER('RPM') AND OBJECT_TYPE IN ('TABLE','SEQUENCE','PACKAGE','FUNCTION','PROCEDURE','TYPE')
    minus
    select synonym_name from dba_SYNONYMS WHERE TABLE_OWNER=UPPER('RPM');