select username,machine,server,count(*) from v$session
group by username,machine,server
order by server desc;

SELECT NAME "NAME", SUBSTR(NETWORK,1,23) "PROTOCOL", OWNED, 
STATUS "STATUS", (BUSY/(BUSY + IDLE)) * 100 "%TIME BUSY" 
FROM V$DISPATCHER;


SELECT MAXIMUM_CONNECTIONS "MAX CONN", MAXIMUM_SESSIONS "MAX SESS", 
SERVERS_STARTED "STARTED", SERVERS_TERMINATED "TERMINATED", 
SERVERS_HIGHWATER "HIGHWATER" 
FROM V$SHARED_SERVER_MONITOR;

