SELECT 'ALTER INDEX '||a.OWNER||'.'||a.INDEX_NAME||' REBUILD ONLINE ;' col1 FROM dba_indexes a WHERE  status='UNUSABLE'
union all
SELECT 'ALTER INDEX '||a.INDEX_OWNER||'.'||a.INDEX_NAME||' REBUILD  PARTITION ONLINE '||PARTITION_NAME||'  ;' col1 FROM dba_ind_partitions a WHERE  status='UNUSABLE'
union all
SELECT 'ALTER INDEX '||a.INDEX_OWNER||'.'||a.INDEX_NAME||' REBUILD  SUBPARTITION ONLINE '||SUBPARTITION_NAME ||'  ;' col1 FROM dba_ind_subpartitions a WHERE  status='UNUSABLE'


SELECT 'ALTER INDEX '||a.OWNER||'.'||a.INDEX_NAME||' REBUILD  parallel 16 nologging ;' col1 FROM dba_indexes a WHERE  status='UNUSABLE'
union all
SELECT 'ALTER INDEX '||a.INDEX_OWNER||'.'||a.INDEX_NAME||' REBUILD  PARTITION '||PARTITION_NAME||'  ;' col1 FROM dba_ind_partitions a WHERE  status='UNUSABLE'
union all
SELECT 'ALTER INDEX '||a.INDEX_OWNER||'.'||a.INDEX_NAME||' REBUILD  SUBPARTITION '||SUBPARTITION_NAME ||'  ;' col1 FROM dba_ind_subpartitions a WHERE  status='UNUSABLE'



SELECT 'ALTER INDEX '||a.OWNER||'.'||a.INDEX_NAME||' REBUILD  TABLESPACE '||TABLESPACE_NAME||' ;' col1 FROM dba_indexes a WHERE  status='UNUSABLE'
union all
SELECT 'ALTER INDEX '||a.INDEX_OWNER||'.'||a.INDEX_NAME||' REBUILD  PARTITION '||PARTITION_NAME||' TABLESPACE '||TABLESPACE_NAME||' ;' col1 FROM dba_ind_partitions a WHERE  status='UNUSABLE'
union all
SELECT 'ALTER INDEX '||a.INDEX_OWNER||'.'||a.INDEX_NAME||' REBUILD  PARTITION '||PARTITION_NAME||' SUBPARTITION '||SUBPARTITION_NAME ||' TABLESPACE '||TABLESPACE_NAME||' ;' col1 FROM dba_ind_subpartitions a WHERE  status='UNUSABLE'


select 'ALTER TABLE '||OWNER||'.'||TABLE_NAME|| ' LOGGING;' NOLOGGING FROM DBA_TABLES WHERE LOGGING='NO' AND TEMPORARY='N' AND OWNER NOT IN ('SYS','SYSTEM','DBSNMP') 
union 
SELECT  'ALTER TABLE '||TABLE_OWNER||'.'||TABLE_NAME||' MODIFY PARTITION '||PARTITION_NAME||' LOGGING;' NOLOGGING FROM DBA_TAB_PARTITIONS WHERE LOGGING='NO' AND TABLE_OWNER NOT IN ('SYS','SYSTEM','DBSNMP') 
union 
select 'ALTER INDEX '||OWNER||'.'||INDEX_NAME|| ' LOGGING;' from dba_indexes where partitioned='NO' and logging='NO' and INDEX_TYPE not in ('BITMAP')AND TABLESPACE_NAME NOT IN ('SYSAUX')AND OWNER NOT IN ('SYS','SYSTEM','DBSNMP') 
union 
SELECT  'ALTER INDEX '||INDEX_OWNER||'.'||INDEX_NAME||' MODIFY PARTITION '||PARTITION_NAME||' LOGGING;' NOLOGGING FROM DBA_IND_PARTITIONS WHERE LOGGING ='NO' AND INDEX_OWNER NOT IN ('SYS','SYSTEM','DBSNMP') 
union 
select 'ALTER TABLESPACE '||TABLESPACE_NAME|| ' LOGGING;' NOLOGGING FROM DBA_TABLESPACES WHERE LOGGING='NOLOGGING' AND CONTENTS='PERMANENT' AND TABLESPACE_NAME NOT IN ('SYS','SYSTEM','DBSNMP');